import { getSiteUrl } from "@/lib/env";

export function GET() {
  const siteUrl = getSiteUrl();

  const body = `# ClearMeta — AI Metadata Remover
# ${siteUrl}

> ClearMeta removes C2PA Content Credentials, EXIF, and XMP AI tags from images generated by ChatGPT, DALL·E, Midjourney, Adobe Firefly, and similar tools. Free automatic processing. Pro Verify detects SynthID and C2PA via OpenAI.

## Product

- Free tool: ${siteUrl}/app — upload images, automatic metadata scan and removal, batch ZIP download
- Pro Verify: ${siteUrl}/verify — SynthID + C2PA detection ($9/mo, usage-based checks)
- Deep Clean beta: ${siteUrl}/app/deep-clean — experimental SynthID disruption (not guaranteed)

## Key pages

- Home: ${siteUrl}/
- Remove AI metadata: ${siteUrl}/remove-ai-metadata
- AI metadata remover (free tool): ${siteUrl}/app
- Remove ChatGPT metadata: ${siteUrl}/remove-chatgpt-metadata
- Remove C2PA / content credentials: ${siteUrl}/remove-c2pa-metadata
- Remove Midjourney metadata: ${siteUrl}/remove-midjourney-metadata
- SynthID remover guide: ${siteUrl}/remove-synthid-metadata
- FAQ: ${siteUrl}/faq
- Privacy: ${siteUrl}/privacy
- Terms: ${siteUrl}/terms
- Security: ${siteUrl}/security

## Supported formats

JPEG, PNG, WebP, TIFF, AVIF, and HEIC — up to 50MB per file.

## What we remove (metadata)

C2PA/JUMBF Content Credentials, EXIF, XMP tags including trainedAlgorithmicMedia, software agent, issuer, model identifiers.

## What we do NOT guarantee

SynthID is pixel-embedded, not metadata. Standard cleaning does not remove SynthID. Deep Clean beta is experimental.

## Contact

- Privacy: privacy@clearmeta.app
- Security: security@clearmeta.app
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
